source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-theme-console"

group :jekyll_plugins do
  gem "jekyll-feed"
end

# Required for Ruby 3.4+
gem "csv"
gem "logger"
gem "base64"
gem "bigdecimal"
gem "webrick"
